#!/usr/bin/env python
# vim: fileencoding=utf-8 et sw=4 ts=4 tw=80:

# python-quilt - A Python implementation of the quilt patch system
#
# Copyright (C) 2012  Björn Ricks <bjoern.ricks@googlemail.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.

# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 
# 02110-1301 USA

import sys
import os.path

import quilt.cli.applied
import quilt.cli.push
import quilt.cli.top
import quilt.cli.series
import quilt.cli.pop
import quilt.cli.patchimport
import quilt.cli.unapplied
import quilt.cli.new

from quilt.error import QuiltError

commands = {
            "push" : quilt.cli.push.parse,
            "pop" : quilt.cli.pop.parse,
            "applied" : quilt.cli.applied.parse,
            "unapplied" : quilt.cli.unapplied.parse,
            "top" : quilt.cli.top.parse,
            "series" : quilt.cli.series.parse,
            "import" : quilt.cli.patchimport.parse,
            "new" : quilt.cli.new.parse,
        }

def usage():
    print "%s command [--help] ..." % (os.path.basename(sys.argv[0]))
    print "Available commands:"
    for cmd in sorted(commands.keys()):
        print "\t", cmd

def main():
    if not len(sys.argv) > 1:
        usage()
        sys.exit(1)

    cmd = sys.argv[1]
    args = sys.argv[2:]

    try:
        parse = commands.get(cmd)
        if not parse:
            print "command %s not known." % cmd
            usage()
            sys.exit(2)
        parse(args)
    except QuiltError, e:
        print e
        sys.exit(1)

if __name__ == "__main__":
        main()
